
import Header from "@/components/Navigation/Header";
import { createClient } from '../../utils/supabase/client'

import { redirect } from 'next/navigation'
import { getSession } from '../../utils/supabase/server'
import { supabase } from "@/lib/supabase";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getSession()

  if (!session) {
      redirect('/login')
    }

  if (session) {
      console.log("SESSIQQ", session);
  }

  return (
    <html lang="en">
      <head>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
